spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yan
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
#      password: yannqing
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 8
          min-idle: 0
      timeout: 0
mybatis:
  type-aliases-package: com.yannqing.pojo
  configuration:
      #??????????
    map-underscore-to-camel-case: true
